RESPUESTAS = {
    "no carga": "Recarga la página con Ctrl+F5.",
    "olvidé mi contraseña": "Puedes restablecerla desde /reset-password.",
    "error 404": "La página solicitada no se encontró.",
    "contacto": "Escríbenos a soporte@tudominio.com.",
    "¿cómo cambio de divisa?": "Ve al apartado ‘Convertir’ y selecciona la divisa que quieres cambiar.",
    "¿qué tasas aplican?": "Las tasas se muestran antes de confirmar la operación.",
    "¿cuánto tarda la transferencia?": "Depende del banco, pero normalmente 1‑3 días hábiles.",
    "¿hay comisión?": "Sí, cobramos una comisión mínima según el monto de cambio.",
    "¿es seguro?": "Sí, usamos cifrado SSL y cumplimos con las normativas de protección de datos.",
    "¿qué documentos piden?": "Documento de identidad válido y comprobante de residencia.",
    "¿puedo cancelar?": "Solo antes de que hayamos procesado tu cambio.",
    "¿y si la tasa cambia?": "La tasa se fija al aceptar la operación.",
    "¿qué pasa si ingreso mal los datos?": "Contacta soporte inmediatamente para corregir errores.",
    "¿puedo cambiar sin cuenta?": "No, necesitas crear una cuenta para operar.",
    "¿mi dinero esta protegido?": "Sí, tus fondos están en cuentas segregadas y reguladas.",
    "¿qué regulacione aplican?": "Operamos bajo la regulación financiera vigente en la UE.",
    "¿qué pasa si mi banco rechaza la transacción?": "Te devolvemos el importe menos cualquier comision bancaria.",
    "¿hay límtes de cambio?": "Sí, hay montos mínimos y máximos por transacción.",
    "¿puedo usar PayPal?": "Depende de tu país, algunas divisas soportan PayPal.",
    "¿aceptan criptomonedas?": "No, solo divisas fiat.",
    "¿qué pasa con los impuestos?": "Eres responsable de declarar según la legislación fiscal de tu país.",
    "¿tengo soporte 24/7?": "Sí, tenemos chat en vivo todos los días.",
    "error de autenticación": "Usuario o contraseña incorrectos.",
    "¿cómo verifico mi cuenta?": "Sube una foto de tu documento y un selfie.",
    "¿y si pierdo acceso al correo?": "Contáctanos con prueba de identidad para actualizar.",
    "¿almacenan mis datos?": "Solo los necesarios para cumplir con la ley KYC/AML.",
    "¿se pueden ver mis transacciones?": "Sí, todas las operaciones aparecen en tu historial.",
    "¿tengo seguro?": "No ofrecemos seguro, pero usamos prácticas de seguridad robustas.",
    "¿qué hago si detecto fraude?": "Reporta inmediatamente a soporte@tudominio.com.",
    "perfil bloqueado": "Tu cuenta está en revisión por actividad sospechosa.",
    "¿cómo retiro fondos?": "Desde ‘Retirar’ selecciona método y destinatario.",
    "¿me cobran al retirar?": "Sí, puede aplicarse una comisión de retirada.",
    "¿cuáles divisas soportan?": "Soportamos EUR, USD, GBP, y otras 20+ divisas.",
    "¿puedo cambiar grandes cantidades?": "Si, pero puede que pidamos más verificación.",
    "¿qué pasa si demoro en verificar?": "Tu cuenta estará en modo limitado hasta que completes verificación.",
    "¿las tasas pueden cambiar?": "Sí, sin previo aviso; las tasas actuales están visibles siempre.",
    "¿hay servicio telefónico?": "Sí, solo en horario laboral: lunes a viernes 9‑18h.",
    "problema con el depósito": "Confirma que usaste los datos correctos, o escríbenos.",
    "problema con la conversión": "Si la tasa no coincide, revisa la hora de cotización.",
    "¿cómo puedo quejarme?": "Envía un correo a reclamaciones@tudominio.com.",
    "¿qué leyes nos regulan?": "Nos regimos por leyes de la Unión Europea y local en tu país.",
    "política de privacidad": "Tus datos se usan sólo para cumplir con normativa y no se venden.",
    "terminos y condiciones": "Consulta nuestros T&C disponibles al pie de página.",
    "fallo en la pasarela de pago": "Intenta otra vez o usa otro método de pago.",
    "¿puedes darme un presupuesto?": "Puedes calcularlo con la herramienta ‘Cotizador’.",
    "¿hay cargos ocultos?": "No, todos los cargos se muestran antes de confirmar.",
    "modificar cambio pendiente": "No se puede modificar una operación una vez iniciada.",
    "¿y si la operación falla?": "Te devolvemos tu dinero menos los costes bancarios aplicables.",
    "¿qué pasa con la divisa local?": "Mostramos equivalencia en tu moneda local por transparencia.",
    "¿qué hora usan para la tasa diaria?": "La tasa se actualiza cada hora basada en mercado interbancario.",
    "¿la web funciona en móvil?": "Sí, está optimizada para dispositivos móviles.",
    "¿el cambio es al instante?": "El cambio se procesa al confirmar la operación, pero puede haber demoras bancarias.",
    "mi nombre sale mal": "Edita tu perfil o contacta a soporte para corrección manual.",
    "¿porqué me piden selfie?": "Es parte del proceso de verificación de identidad obligatorio por ley.",
    "se perdio mi dinero": "Verifica el estado de la transacción y escríbenos si no aparece.",
    "no entiendo como funciona": "Puedes revisar nuestra guía para principiantes o escribirnos tus dudas.",
    "la app se tilda": "Cierra y vuelve a abrir la app, o borra caché.",
    "¿se puede usar en venezuela?": "Sí, pero puede haber restricciones según el método de pago.",
    "¿aceptan pesos colombianos?": "Sí, los COP están disponibles para cambio con ciertas divisas.",
    "¿me pueden bloquear la cuenta?": "Sí, si se detectan actividades sospechosas o violación de términos.",
    "olvidé mi usuario": "Puedes recuperarlo con tu correo electrónico registrado.",
    "cuánto se demoran en verificar?": "Generalmente entre 24 y 48 horas hábiles.",
    "¿por qué piden tantos datos?": "Cumplimos con normativas KYC y prevención de lavado de dinero.",
    "¿puedo operar desde USA?": "Sí, siempre que no estés en un estado restringido.",
    "¿cómo saber si es legal?": "Estamos registrados y regulados por entidades financieras oficiales.",
    "quiero cerrar mi cuenta": "Puedes hacerlo desde tu perfil o enviando una solicitud a soporte.",
    "no veo mi saldo": "Revisa que estés en la cuenta correcta y actualiza la página.",
    "me equivoque en la cuenta de destino": "Escríbenos urgente para ver si se puede revertir.",
    "¿puedo tener 2 cuentas?": "No está permitido tener múltiples cuentas por persona.",
    "¿como evitar estafas?": "Nunca compartas tu contraseña ni datos sensibles.",
    "no se puede entrar": "Asegúrate de estar usando la URL correcta y borra cookies.",
    "¿se puede cambiar a yenes?": "Sí, trabajamos con JPY en montos superiores a 100 USD.",
    "no entiendo la tasa": "La tasa mostrada es la actual del mercado menos nuestra comisión.",
    "quiero hablar con humano": "Nuestro equipo de soporte está disponible por chat y correo.",
    "hay error en el nombre del destinatario": "Verifica los datos antes de confirmar cualquier envío.",
    "porque me cobraron más": "Pueden aplicarse comisiones bancarias adicionales ajenas a nosotros.",
    "el código de verificación no llega": "Revisa spam o espera unos minutos. Si no llega, solicita uno nuevo.",
    "me sale error de red": "Comprueba tu conexión o cambia de navegador.",
    "¿funciona en domingos?": "La plataforma sí, pero algunos bancos no procesan pagos ese día.",
    "se me cerro la sesión": "Por seguridad, cerramos sesiones inactivas después de cierto tiempo.",
    "me equivoqué en el monto": "Las operaciones no pueden modificarse una vez confirmadas.",
    "me llegó menos dinero": "Pueden aplicarse cargos por parte de bancos intermediarios.",
    "no aparece la opción de cambiar": "Asegúrate de haber verificado tu cuenta y tener saldo disponible.",
    "error 500": "Intenta nuevamente más tarde o contacta soporte.",
    "como saber si la tasa es buena": "Compara con el mercado interbancario o plataformas públicas.",
    "me bloquearon sin razón": "Tu cuenta está siendo revisada por el equipo de cumplimiento.",
    "cuanto puedo cambiar por dia": "Depende de tu nivel de verificación.",
    "por qué se cancelo mi operación": "Puede deberse a errores en los datos o sospechas de fraude.",
    "quiero mi dinero de vuelta": "Escríbenos indicando el número de operación y motivo.",
    "puse mal el IBAN": "Si aún no se ha procesado, podemos cancelarla por ti.",
    "no me deja subir documento": "Prueba desde otro navegador o dispositivo.",
    "me dice documento invalido": "Debe estar en alta calidad, legible y sin reflejos.",
    "la web esta lenta": "Podría deberse a mantenimiento o tráfico alto.",
    "¿puedo usar tarjeta de otra persona?": "No, sólo aceptamos tarjetas a tu nombre.",
    "la operación no aparece": "Espera unos minutos o revisa en tu historial.",
    "cobran por convertir?": "Sí, cobramos una pequeña comisión por transacción.",
    "¿me pueden pagar en efectivo?": "No, solo transferencias bancarias o electrónicas.",
    "como agrego una nueva cuenta": "Desde tu perfil, en la sección de cuentas bancarias.",
    "por qué no me deja operar": "Podrías estar limitado por verificación pendiente o límites diarios.",
    "la app no actualiza": "Borra la caché o reinstala la aplicación.",
    "es legal cambiar dolares aca?": "Sí, siempre que cumplas con la normativa local de tu país.",
    "me sale transaccion pendiente": "Es normal, puede tardar unos minutos en completarse.",
    "cambie pero no recibo nada": "Revisa el estado de tu operación en el historial.",
    "puedo usar otra cuenta bancaria?": "Sí, pero debe estar a tu nombre y registrada.",
    "no entiendo el comprobante": "El comprobante muestra los detalles de la operación realizada.",
    "me pide actualizar datos": "Es parte del proceso de cumplimiento regulatorio obligatorio.",
    "como puedo confirmar el envio": "Recibirás un correo de confirmación y aparece en tu panel.",
    "me cobraron 2 veces": "Puede tratarse de una duplicación. Escríbenos con evidencia.",
    "me aparece cuenta inactiva": "Debes reactivar tu cuenta desde el correo enviado.",
    "no puedo subir el selfie": "Asegúrate de permitir acceso a la cámara y buena iluminación.",
    "el pago se quedo colgado": "A veces tarda. Si no avanza en 1 hora, contáctanos.",
    "que hago si no tengo cuenta bancaria": "Necesitas una para recibir o enviar fondos.",
    "puedo enviar a un tercero?": "No, por normativa solo permitimos cuentas a tu nombre.",
    "me equivoqué de moneda": "Una vez confirmada, no se puede cambiar la moneda.",
    "el retiro no llega": "Puede tardar de 1 a 3 días hábiles según el banco receptor.",
    "porque me piden dirección?": "Es requerido por regulación contra lavado de dinero.",
    "es obligatorio verificar?": "Sí, sin verificación no puedes operar por temas legales.",
    "puedo usar cédula vencida?": "No, el documento debe estar vigente.",
    "que pasa si me equivoque de correo?": "Escríbenos desde el correcto con una prueba de identidad.",
    "tengo problemas con IBAN": "Verifica que esté completo y sin espacios ni errores.",
    "puedo usar esta web si soy menor?": "No, debes ser mayor de edad según la ley.",
    "me aparece error al convertir": "Revisa si estás usando un monto dentro del límite.",
    "cual es el mínimo para operar?": "Varía por divisa, pero suele ser de $10 USD o equivalente.",
    "el sistema no reconoce mi tarjeta": "Asegúrate de que sea una tarjeta válida y con fondos.",
    "puedo pagar en bolivares?": "Sí, siempre que esté habilitado en tu país.",
    "aceptan Zelle?": "Sí, pero solo para usuarios verificados.",
    "no quiero dar mis datos": "Sin datos no podemos permitir operaciones por ley.",
    "como recupero mi cuenta": "Haz clic en 'Olvidé mi contraseña' o contacta soporte.",
    "se me olvido la clave": "Usa la opción de restablecer en la página de inicio.",
    "puedo usar VPN?": "No se recomienda. Puede bloquear tu acceso por seguridad.",
    "me dice que excedi el límite": "Intenta con un monto menor o espera al día siguiente.",
    "no recibí correo de confirmación": "Revisa tu carpeta de spam o espera unos minutos.",
    "por qué se pide selfie con documento?": "Para verificar que seas el titular real.",
    "no puedo agregar mi cuenta": "Revisa que los datos estén bien escritos y sin símbolos.",
    "la app me cierra sola": "Actualiza la app o reinstala desde la tienda.",
    "me aparece riesgo alto": "Tu cuenta fue marcada para revisión por el equipo de seguridad.",
    "tengo que pagar impuestos?": "Depende de tu país. Te corresponde declararlos si aplica.",
    "no me deja retirar todo el dinero": "Debes dejar un saldo mínimo o cubrir comisiones.",
    "cuantos cambios puedo hacer por dia?": "No hay límite, pero puede haber restricciones por monto.",
    "como saber si mi transacción se procesó?": "Revisa tu historial o busca el correo de confirmación.",
    "el botón no funciona": "Prueba con otro navegador o limpia caché.",
    "no tengo saldo suficiente": "Recarga tu cuenta antes de intentar otra operación.",
    "cuanto tiempo tarda soporte?": "Respondemos entre 1 y 12 horas, según la demanda.",
    "cual es su licencia?": "Estamos regulados por la autoridad financiera de nuestro país.",
    "puedo hacer cambio de nombre?": "Solo si aportas documentos legales que lo respalden.",
    "no me deja seleccionar divisa": "Puede estar deshabilitada temporalmente.",
    "me aparece 'documento no valido'": "Debe estar en buena calidad, sin manchas ni cortes.",
    "como accedo desde otro país?": "La plataforma está disponible en varios países. Solo inicia sesión.",
    "que pasa si hay un error del sistema?": "Nos haremos responsables si es error interno.",
    "me aparece 'cuenta bajo revisión'": "Tu cuenta está siendo analizada por cumplimiento.",
    "aceptan pagos en efectivo?": "No, solo medios digitales por seguridad.",
    "puedo retirar a tarjeta de credito?": "No, solo a cuentas bancarias por ahora.",
    "porque me pide actualizar selfie?": "Revalidamos tu identidad cada cierto tiempo.",
    "como cierro sesión?": "Desde tu perfil, en el menú superior derecho.",
    "puedo recibir pagos de terceros?": "No, solo se permiten operaciones propias.",
    "mi transacción fue cancelada": "Seguramente no se completó algún paso. Intenta de nuevo.",
    "no se actualiza el saldo": "Puede tardar unos minutos tras procesar el cambio.",
    "por qué cobran comisión?": "Es nuestra forma de sostener la operación del servicio.",
    "hay riesgo de perder dinero?": "No, si usas bien la plataforma y verificas todo.",
    "tienen oficina fisica?": "Somos una plataforma 100% digital.",
    "como ingreso fondos?": "Desde tu panel, haz clic en 'Depositar' y sigue los pasos.",
    "que tipos de cuenta aceptan?": "Cuentas corrientes y de ahorro, a tu nombre.",
    "me rechaza el documento": "Verifica que esté completo, visible y vigente.",
    "tengo cuenta bloqueada": "Contáctanos para conocer el motivo y cómo desbloquearla.",
    "como me registro?": "Haz clic en ‘Crear cuenta’ y completa el formulario.",
    "puedo usar la cuenta de mi esposa?": "No, cada usuario debe usar cuentas a su nombre.",
    "me sale error con monto": "Revisa si estás dentro de los límites permitidos.",
    "el correo dice operación exitosa pero no llega": "Espera hasta 48 horas hábiles, puede estar en proceso.",
    "se cancelo la verificación sola": "Debiste salir del proceso o falló algún paso. Intenta otra vez.",
    "como cambio mi correo?": "Desde tu perfil o enviando solicitud con tu ID.",
    "porque piden selfie con papel y fecha?": "Es un requisito de seguridad para evitar suplantaciones.",
    "mi banco no aparece": "Puedes ingresar los datos manualmente si tu banco no está en la lista.",
    "hay descuentos por volumen?": "Sí, a partir de ciertos montos ofrecemos mejor tasa.",
    "la tasa es fija o variable?": "Se fija en el momento de confirmar la operación.",
    "mi pais no aparece": "Por regulación, algunos países no están habilitados.",
    "como convierto criptomonedas?": "Por ahora no trabajamos con criptoactivos.",
    "porque tengo que declarar mis ingresos?": "Es parte de la regulación fiscal vigente en tu país.",
    "me pide número fiscal": "Algunos países exigen tu NIF o RUT para operar.",
    "me dicen que use otra IP": "Tu IP fue bloqueada por razones de seguridad o país restringido.",
    "no puedo actualizar mis datos": "Prueba desde otro dispositivo o contacta soporte.",
    "como subo mis documentos?": "Desde la sección de verificación, elige el archivo y súbelo.",
    "por qué no aceptan cuentas de Payoneer?": "Solo trabajamos con bancos tradicionales por regulación.",
    "no aceptan Western Union?": "No. Solo transferencias bancarias.",
    "como cambio mi contraseña?": "Desde tu perfil, en 'Seguridad'.",
    "cuánto es el máximo diario?": "Depende de tu país y nivel de verificación.",
    "me aparece 'token inválido'": "El enlace expiró. Solicita uno nuevo.",
    "la pantalla queda en blanco": "Actualiza, cambia de navegador o revisa tu conexión.",
    "me dice que ya tengo una cuenta": "Si olvidaste tus datos, solicita recuperación.",
    "puedo enviar desde cuenta de empresa?": "Solo si está verificada como cuenta corporativa.",
    "aceptan euros en efectivo?": "No, solo transferencias digitales.",
    "¿por qué no puedo hacer cambios hoy?": "Podría ser feriado bancario o mantenimiento de sistema.",
    "se reinicia la app cuando confirmo": "Borra caché o instala la última versión disponible.",
    "no tengo NIE, puedo operar?": "Debes tener un documento oficial de identificación válido.",
    "me pide dirección en inglés": "Si vives fuera de tu país, debes escribir la dirección en el idioma local.",
    "que hago si no tengo recibo de luz?": "Puedes usar otros comprobantes como contrato de alquiler o estado bancario.",
    "el IBAN me da error": "Revisa el formato exacto y sin espacios entre los números.",
    "no entiendo la confirmación por SMS": "Debes ingresar el código que te llegó a tu celular.",
    "puedo usar la plataforma sin verificar?": "Solo podrás ver las tasas, no operar.",
    "cuanto tarda un reembolso?": "Puede tardar de 3 a 10 días hábiles, según el método original.",
    "por qué no aceptan mi pasaporte?": "Debe estar vigente, legible y sin bordes cortados.",
    "como subo mis documentos desde el celular?": "Desde el navegador móvil o app, accede a Verificación y toma una foto.",
    "me aparece tasa incorrecta": "Actualiza la página o vuelve a cargar la cotización.",
    "la app me pide ubicación": "Es necesaria para validar tu país de operación según regulación.",
    "puedo operar desde Cuba?": "No, Cuba está restringida por normativa internacional.",
    "hay limite mensual?": "Sí, y depende del país, nivel de verificación y tipo de operación.",
    "se perdieron mis fondos?": "Es poco probable. Escríbenos con el número de operación.",
    "que pasa si uso datos falsos?": "Tu cuenta será suspendida y podrías ser reportado.",
    "puedo enviar dinero a mi empresa?": "Solo si tu cuenta fue verificada como corporativa.",
    "como elimino una cuenta bancaria registrada?": "Desde tu perfil, en 'Cuentas bancarias'.",
    "me dice que ya verifiqué pero me vuelve a pedir": "Puede ser una revalidación periódica por normativa.",
    "la plataforma es gratuita?": "No. Aplicamos una pequeña comisión por operación.",
    "por qué me sale monto inválido?": "Debes usar el formato correcto y estar dentro de los límites.",
    "puedo recibir pagos en mi cuenta?": "No usamos la plataforma como pasarela de cobros, solo para cambios.",
    "me pide foto del documento por ambos lados": "Sí, es obligatorio mostrar ambos lados para verificar identidad.",
    "puedo pagar desde una cuenta compartida?": "Solo si tú eres titular conjunto y puedes demostrarlo.",
    "como actualizo mi dirección?": "Desde tu perfil, en la sección de información personal.",
    "me dice que ya use ese número": "Probablemente ya creaste una cuenta antes.",
    "mi selfie fue rechazada": "Debe ser clara, sin filtros, sin lentes ni gorros.",
    "no entiendo cómo usar la tasa": "La tasa de cambio es el valor de tu divisa respecto a la que recibirás.",
    "me aparece error 403": "Tu IP fue restringida por intento de acceso no autorizado.",
    "puedo abrir cuenta con pasaporte extranjero?": "Sí, si resides legalmente en el país y puedes comprobarlo.",
    "me pide residencia fiscal": "Es obligatoria para cumplir normativa internacional (FATCA/CRS).",
    "no puedo ver historial": "Asegúrate de estar logueado con la cuenta correcta.",
    "por qué me piden tantos pasos?": "Es por ley. Buscamos protegerte del fraude y cumplir normativas.",
    "puedo usar una cuenta bancaria antigua?": "Sí, siempre que esté activa y sea a tu nombre.",
    "puedo usar un correo diferente al del registro?": "No, debes solicitar cambio oficialmente por seguridad.",
    "como elimino mi cuenta?": "Solicita la baja desde tu perfil o por correo a soporte.",
    "me aparece 'verificación en progreso' por días": "Estamos revisando manualmente tu caso. Agradecemos la paciencia.",
    "mi banco no acepta fondos en esa moneda": "Debes usar una cuenta multimoneda o elegir otra divisa.",
    "me pide adjuntar prueba de origen de fondos": "Es parte de nuestras políticas contra lavado de dinero.",
    "puedo tener dos perfiles?": "No, está prohibido y puede causar bloqueo de ambas cuentas.",
    "me dice que la tarjeta no coincide": "Solo puedes usar tarjetas a tu nombre registrado.",
    "no se puede procesar el cambio ahora": "Intenta más tarde. Puede ser por mantenimiento o tasa inestable.",
    "puedo operar desde una empresa offshore?": "No aceptamos cuentas vinculadas a jurisdicciones opacas.",
    "me pidieron datos adicionales": "Es parte del proceso de validación reforzada.",
    "me dicen que mi foto es borrosa": "Súbela nuevamente asegurándote que sea nítida y sin reflejos.",
    "se borró mi operación": "Revisa si fue cancelada automáticamente por inactividad.",
    "por qué no me devuelven el 100%?": "Algunos costos de procesamiento no son reembolsables.",
    "que significa cuenta inactiva?": "No ha tenido movimientos en más de 6 meses.",
    "no entiendo la comisión": "Se calcula sobre el monto total y se muestra antes de confirmar.",
    "me piden un comprobante que no tengo": "Consulta qué alternativas aceptamos para tu país.",
    "puedo usar cuenta bancaria de un familiar?": "No. Solo cuentas personales tuyas.",
    "tienen soporte en español?": "Sí, de lunes a viernes, vía chat y correo.",
    "me bloquearon temporalmente": "Tu cuenta se congeló por actividad inusual. Revisa tu correo.",
    "puedo ver la tasa antes de cambiar?": "Claro. Está disponible en la calculadora de inicio.",
    "porque no permiten más de 3 intentos?": "Por seguridad. Evitamos intentos automatizados o fraudulentos.",
    "no se acredita el pago": "Verifica si el banco lo procesó correctamente. A veces tarda.",
    "como cambio la divisa por defecto?": "Desde tu panel, selecciona 'Preferencias de cuenta'.",
    "mi teléfono ya no sirve": "Puedes actualizar el número si verificas tu identidad.",
    "me dicen que el documento no es aceptado": "Debe ser emitido por autoridad oficial y estar vigente.",
    "porque piden factura de servicios?": "Para validar tu lugar de residencia.",
    "puedo operar desde el extranjero?": "Sí, mientras no estés en países restringidos.",
    "tengo que declarar al fisco esto?": "Sí, depende de la legislación de tu país.",
    "me aparece 'cuenta duplicada'": "Ya tienes una cuenta registrada con ese correo o teléfono.",
    "como ingreso desde una computadora nueva?": "Se te pedirá verificación adicional por seguridad.",
    "porque me rechazan la cuenta bancaria?": "Debe estar activa, a tu nombre, y no tener errores.",
    "me equivoqué en mi nombre": "Puedes solicitar corrección con documento que lo justifique.",
    "puedo cambiar el país de residencia?": "Sí, si te mudaste legalmente. Aporta prueba de ello.",
    "puedo cambiar divisa entre cuentas mías?": "Sí, puedes hacer transferencias internas entre tus cuentas.",
    "porque no aceptan transferencias en efectivo?": "Por regulación anti lavado, solo permitimos trazabilidad bancaria.",
    "como saber si fui verificado?": "Recibirás un correo de confirmación y verás una marca en tu perfil.",
    "me dice que no puedo operar desde mi país": "Puede estar restringido por sanciones internacionales.",
    "no me deja hacer más cambios": "Probablemente llegaste a tu límite diario o mensual.",
    "porque me piden actividad económica?": "Es obligatorio declarar el origen de tus fondos.",
    "puedo operar como autónomo?": "Sí, si registras tus datos fiscales correspondientes.",
    "me cancelaron sin avisar": "Revisa tu correo. Siempre notificamos el motivo.",
    "la transferencia llegó incompleta": "Contacta a tu banco, puede haber descuentos por parte del intermediario.",
    "me llegó doble notificación": "Puede ser un error temporal, solo una debe ser válida.",
    "me pide declarar beneficiario final": "Es obligatorio si operas con cuentas corporativas.",
    "me exigen subir documento local": "Algunos países exigen identificación emitida localmente.",
    "puedo poner un apoderado?": "No. Solo titulares pueden operar directamente.",
    "como imprimo mi comprobante?": "Desde el historial, haz clic en la operación y selecciona 'Descargar'.",
    "me pide actualizar documento vencido": "Debes subir uno vigente para mantener tu cuenta activa.",
    "que pasa si fallezco?": "Tus herederos deberán presentar documentación legal para recuperar fondos.",
    "como confirmo si fue enviado?": "Revisa el estado en tu historial o correo de confirmación.",
    "cuanto tiempo tardan en procesar verificación?": "De 24 a 72 horas hábiles normalmente.",
    "me piden validación bancaria": "Es para evitar fraudes y confirmar que tú controlas la cuenta.",
    "me llegó un correo que no entendí": "Reenvíalo a soporte para ayudarte a interpretarlo.",
    "no aparece la opción que necesito": "Puede no estar habilitada para tu país o tipo de cuenta.",
    "el soporte no me responde": "Puede haber alta demanda. Ten paciencia, responderemos pronto.",
    "mi operación fue marcada como riesgosa": "Estamos evaluando si cumple nuestras políticas de cumplimiento.",
    "porque me pide código postal?": "Es necesario para geolocalización y validación fiscal.",
    "que hago si se me bloqueó el retiro?": "Escríbenos con tu identificación y motivo del retiro.",
    "por qué me piden firmar un documento?": "Es una autorización de uso y verificación exigida por ley.",
    "puedo operar desde un cyber café?": "Sí, pero asegúrate de cerrar sesión por seguridad.",
    "me aparece 'operación fallida sin motivo'": "Puede ser un error temporal, intenta en unos minutos.",
    "por qué no hay atención telefónica?": "Priorizamos soporte digital para mayor rapidez y trazabilidad.",
    "puedo usar mi cuenta de trabajo?": "Solo si está a tu nombre personal, no corporativo.",
    "me cobran por recibir dinero?": "No nosotros, pero tu banco podría hacerlo.",
    "hay horario para hacer cambios?": "La plataforma está disponible 24/7, salvo mantenimientos.",
    "puedo tener cuenta en euros y dólares?": "Sí, puedes operar con múltiples divisas.",
    "la tasa es la misma que Google?": "No, usamos tasas interbancarias con un margen aplicado.",
    "puedo operar aunque esté desempleado?": "Sí, si puedes demostrar origen lícito de fondos.",
    "no me acuerdo si ya me registré": "Intenta recuperar tu cuenta con tu correo o número.",
    "como sé si están regulados?": "Consulta nuestro número de registro en el pie de página.",
    "por qué tarda tanto la respuesta?": "Algunos casos requieren revisión manual por el equipo legal.",
    "puedo subir mi documento escaneado?": "Preferimos foto clara, pero aceptamos escaneo si es legible.",
    "mi selfie sale muy oscura": "Usa luz natural o una lámpara frontal para iluminar tu rostro.",
    "puedo recibir ayuda por WhatsApp?": "No, solo usamos canales oficiales para garantizar tu privacidad.",
    "por qué me preguntan si soy políticamente expuesto?": "Es requerido por ley para evaluar riesgo financiero.",
    "como veo mis límites actuales?": "Están disponibles en la sección de perfil > límites.",
    "por qué no me deja ingresar montos decimales?": "Usa punto (.) como separador en vez de coma (,).",
    "me confundí de tipo de cuenta": "Puedes modificarlo desde el panel si aún no operaste.",
    "puedo pausar mi cuenta?": "Sí, solicítalo desde el perfil o escribiendo a soporte.",
    "me registré pero nunca verifiqué": "Tu cuenta está inactiva. Completa la verificación para operar.",
    "mi país cambió de moneda": "Actualiza tu información fiscal y bancaria desde tu perfil.",
    "puedo vincular mi billetera digital?": "Solo si está verificada y es compatible con nuestras políticas.",
    "no entiendo el aviso de riesgo": "Indica que hay condiciones que podrían afectar tu operación.",
    "por qué piden nacionalidad?": "Es necesaria para cumplimiento fiscal y de seguridad.",
    "mi celular fue robado": "Cambia tu clave desde otro dispositivo y contáctanos.",
    "cómo activo la autenticación en 2 pasos?": "Ve a configuración > seguridad > activar 2FA.",
    "me banearon por 'comportamiento sospechoso'": "Escríbenos si crees que fue un error, evaluaremos tu caso.",
    "cuál es su política de cookies?": "Está detallada en nuestro sitio en el enlace legal al pie.",
    "cuántos idiomas ofrecen?": "Actualmente en español, inglés, portugués y francés.",
    "el sitio está caído": "Probablemente estamos en mantenimiento. Intenta más tarde.",
    "puedo hacer cambios por teléfono?": "No, todas las operaciones deben hacerse por la plataforma.",
    "por qué me piden ingresos estimados?": "Es obligatorio para evaluación de perfil financiero.",
    "me aparece 'cuenta inhabilitada por riesgo externo'": "Tu IP o actividad fue detectada como potencialmente riesgosa.",
    "puedo operar desde el mismo correo de mi hermano?": "No, cada usuario debe tener datos únicos y personales.",
    "la plataforma detectó actividad sospechosa": "Tu cuenta fue suspendida preventivamente para protegerla.",
    "cómo cancelo una operación pendiente?": "Desde el historial, si aún está en espera.",
    "me llegó un SMS sospechoso": "No respondas. Escríbenos para verificar si fue legítimo.",
    "mi tasa fue mejor que la publicada": "Ocasionalmente aplicamos mejoras automáticas por promociones.",
    "puedo conectar mi cuenta bancaria directamente?": "Sí, con los métodos de open banking autorizados.",
    "por qué me piden ocupación laboral?": "Es parte de la validación del perfil para evitar fraudes.",
    "se me borró todo el historial": "Verifica que estás usando la cuenta correcta.",
    "me cobraron por error": "Escríbenos con los detalles y revisaremos el caso.",
    "por qué aparece mi saldo en negativo?": "Podría deberse a un ajuste o cargo pendiente.",
    "puedo hacer una operación programada?": "Sí, desde el panel selecciona ‘programar cambio’.",
    "porque no aceptan bancos fintech?": "Algunos bancos digitales no cumplen requisitos regulatorios.",
    "me bloquearon por VPN": "Desactiva la VPN y accede normalmente.",
    "por qué me piden subir la cédula otra vez?": "Verificamos identidad periódicamente según la ley.",
    "hay promociones o bonificaciones?": "Sí, revisa la sección de promociones en tu panel.",
    "me aparece tasa congelada": "Eso significa que puedes usarla por tiempo limitado antes que cambie.",
    "mi país cambió de regulación": "Podemos solicitarte documentos nuevos para cumplirla.",
    "por qué tengo que aceptar términos nuevos?": "Cada cierto tiempo actualizamos nuestros términos legales.",
    "se puede operar sin cuenta bancaria?": "No, por seguridad y cumplimiento necesitamos trazabilidad bancaria.",
    "cuánto cuesta mantener la cuenta?": "Nada. Solo se cobran comisiones cuando haces operaciones.",
    "puedo tener cuenta personal y de empresa?": "Sí, pero con correos y datos totalmente separados.",
    "por qué no funciona mi método de pago?": "Puede haber sido bloqueado por tu entidad financiera.",
    "como verifico si un correo es real?": "Todos nuestros correos vienen desde @tudominio.com.",
    "por qué veo dos tasas diferentes?": "Una es la interbancaria y otra con nuestra comisión incluida.",
    "puedo operar desde un fideicomiso?": "No admitimos cuentas de fideicomisos o fondos no regulados.",
    "me equivoqué al registrarme como empresa": "Puedes pedir el cambio si aún no hiciste ninguna operación.",
    "tengo problemas para adjuntar archivos": "Intenta con otro navegador o reduce el tamaño del archivo.",
    "me sale 'documento duplicado en otro usuario'": "Tu documento ya está en otra cuenta. Contacta soporte.",
    "cómo accedo al área de cumplimiento?": "No es pública. Solo se activa en revisiones específicas.",
    "por qué aparece que mi IP es de otro país?": "Tu proveedor puede estar usando una IP extranjera.",
    "hay cargos por inactividad?": "Sí, si no usas la cuenta por más de 12 meses.",
    "puedo operar si estoy en lista negra crediticia?": "Sí, siempre que tus fondos tengan origen lícito.",
    "cómo actualizo mis datos fiscales?": "Desde tu perfil, sección fiscal o escribiendo a soporte.",
    "puedo tener saldo en varias monedas?": "Sí, manejamos balances multimoneda.",
    "por qué no puedo enviar fondos a terceros?": "Por cumplimiento KYC/AML solo permitimos auto-transferencias.",
    "tienen sistema de referidos?": "Sí, consulta los términos en la sección ‘Invita y gana’.",
    "cómo sé si están auditados?": "Publicamos informes de transparencia regularmente en el sitio.",
    "me pide fuente de ingresos pero soy informal": "Puedes declarar tu actividad económica como independiente.",
    "mi cuenta fue dada de baja sin aviso": "Probablemente por inactividad o incumplimiento. Escríbenos.",
    "puedo operar con ITIN en vez de SSN?": "Sí, en algunos países aceptamos ambos según el caso.",
    "me sale error de validación 006": "Es un error común de formato. Verifica tus datos ingresados.",
    "por qué no aceptan nombres con acentos?": "Nuestro sistema aún no los reconoce bien, omite los acentos.",
    "cómo cierro sesión automáticamente?": "Activa cierre automático en tu configuración de seguridad.",
    "la tasa se actualiza en tiempo real?": "Sí, aunque puede haber segundos de diferencia según el tráfico.",
    "por qué me dicen que estoy en una lista de control?": "Tu documento coincide con bases de datos internacionales.",
    "cuántas veces puedo fallar mi clave?": "5 veces. Luego se bloquea por seguridad.",
    "puedo pagar comisión con otra divisa?": "Sí, se convierte automáticamente al momento de cobrarla.",
    "qué pasa si no acepto los términos?": "No podrás seguir usando la plataforma legalmente.",
    "me sale error 999 sin explicación": "Es un error interno. Escríbenos con captura de pantalla.",
    "por qué se rechaza el contrato firmado digitalmente?": "Debes usar nuestra herramienta de firma, no externa.",
    "puedo recibir saldo desde el extranjero?": "Sí, siempre que sea desde una cuenta bancaria tuya.",
    "qué pasa si me hackean la cuenta?": "Actuamos rápido, pero tú debes tener autenticación activada.",
    "por qué no puedo agregar nueva tarjeta?": "Máximo 3 tarjetas por usuario están permitidas.",
    "me dice que la operación expiró": "Tenías tiempo límite para completarla y se cerró automáticamente.",
    "cuál es el horario de soporte humano?": "De lunes a viernes de 9:00 a 18:00 (hora local).",
    "por qué me pide subir el mismo documento 3 veces?": "Tal vez no fue legible o no cumplió los requisitos.",
    "puedo operar si no tengo dirección fija?": "Necesitas una dirección válida para verificar tu residencia.",
    "cómo sé si mis fondos están seguros?": "Cumplimos estándares internacionales de seguridad financiera.",
    "Hola Alcides": "https://res.cloudinary.com/ddmzvbbef/image/upload/v1758712670/k3zzsbpjgbqkixhjtjy7.png",
    "Hola Marcos ": "https://res.cloudinary.com/ddmzvbbef/image/upload/v1758713747/nfpdulzt8teptbynmpgo.png",
    "Hola Ruben " : "https://res.cloudinary.com/ddmzvbbef/video/upload/v1758270264/Perrete_xicvam.mp4"
    
    }
